---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: argo-workflows
spec:
  interval: 30m
  targetNamespace: argo-workflows
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  kubeConfig:
    secretRef:
      name: cluster-kubeconfig
  chart:
    spec:
      chart: argo-workflows
      version: "0.46.4"
      sourceRef:
        kind: HelmRepository
        name: argo
      interval: 12h
  values:
    crds:
      install: true
    singleNamespace: false
    workflow:
      serviceAccount:
        create: true
        name: argo-workflow
    controller:
      replicas: 1
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          memory: 256Mi
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containerSecurityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
      workflowDefaults:
        spec:
          securityContext:
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
    server:
      replicas: 1
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          memory: 128Mi
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containerSecurityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
    executor:
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          memory: 128Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
    artifactRepository:
      s3:
        bucket: argo-artifacts
        endpoint: seaweedfs-filer.seaweedfs-system.svc.cluster.local:8333
        insecure: true
        accessKeySecret:
          name: argo-artifacts-s3
          key: accessKey
        secretKeySecret:
          name: argo-artifacts-s3
          key: secretKey
