kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: axon
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 80
        hostPort: 8881
        protocol: TCP
      - containerPort: 443
        hostPort: 8444
        protocol: TCP
