apiVersion: meta.pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-xtenant
  annotations:
    meta.crossplane.io/maintainer: mdaops
    meta.crossplane.io/source: github.com/mdaops/synapse/cortex
    meta.crossplane.io/description: Composition function for Tenant resources
