---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tenants
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  interval: 10m
  retryInterval: 1m
  timeout: 5m
  prune: true
  wait: true
  path: ./deploy/tenants
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-controllers
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  dependsOn:
    - name: tenants
  interval: 10m
  retryInterval: 1m
  timeout: 5m
  prune: true
  wait: true
  path: ./deploy/infra-controllers
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-configs
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  dependsOn:
    - name: infra-controllers
  interval: 10m
  retryInterval: 1m
  timeout: 5m
  prune: true
  wait: true
  path: ./deploy/infra-configs
  sourceRef:
    kind: GitRepository
    name: flux-system
