---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kserve
spec:
  interval: 1h
  url: oci://ghcr.io/kserve/charts
  type: oci
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kserve-crd
spec:
  interval: 30m
  targetNamespace: kserve
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  kubeConfig:
    secretRef:
      name: cluster-kubeconfig
  chart:
    spec:
      chart: kserve-crd
      version: "v0.16.0"
      sourceRef:
        kind: HelmRepository
        name: kserve
      interval: 12h
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kserve
spec:
  interval: 30m
  targetNamespace: kserve
  dependsOn:
    - name: kserve-crd
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  kubeConfig:
    secretRef:
      name: cluster-kubeconfig
  chart:
    spec:
      chart: kserve
      version: "v0.16.0"
      sourceRef:
        kind: HelmRepository
        name: kserve
      interval: 12h
  values:
    kserve:
      controller:
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            memory: 512Mi
    modelmesh:
      enabled: false
